### ISSUE TITLE
How is mkiss installed?

### ISSUE THREAD

**Issue by PetrifiedOak** [mdartmann/mkiss#2]
I am interested in switching to mkiss, but i looked around and don't see any tarballs. how are you supposed to install it?

**Comment by mdartmann** [comment]
Hi @PetrifiedOak ,

thank you for reaching out! I have not published any tarballs yet as there hasn't been demand, however, I can create one right now if you'd like. I'm not sure how streamlined the process will be as I've never created one but I'll do my best.

Would you like a minimal environment to get you started or a whole system with GNOME and the likes? I have a few updates lined up that I'd like to publish first, but I can create a release 0.1 afterwards. It's actually quite fitting as I'm planning to migrate everything over to OpenSSL3 soon.

**Comment by PetrifiedOak** [comment]
> Hi @PetrifiedOak ,
> 
> thank you for reaching out! I have not published any tarballs yet as there hasn't been demand, however, I can create one right now if you'd like. I'm not sure how streamlined the process will be as I've never created one but I'll do my best.
> 
> Would you like a minimal environment to get you started or a whole system with GNOME and the likes? I have a few updates lined up that I'd like to publish first, but I can create a release 0.1 afterwards. It's actually quite fitting as I'm planning to migrate everything over to OpenSSL3 soon.

Yes, thank you! I would love to have a minimal tarball so I can go my own way from there.

**Comment by mdartmann** [comment]
Hi @PetrifiedOak ,

sorry that this took a couple days, I wanted to get it right.

Please try the released tarball when you have some time and let me know if everything works as expected.

Thanks again for your interest!

**Comment by mdartmann** [comment]
Closing this issue now. If you need anything else please tell me.
